# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_keepers', '0003_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
