# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_keepers', '0004_expense_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense',
        ),
    ]
