# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_keepers', '0007_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
