# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_keepers', '0008_auto_20170520_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2017', '2017'), ('2018', '2018')], default=2017, max_length=2)),
            ],
        ),
    ]
