# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_keepers', '0009_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=9),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018')], default=2017, max_length=4),
        ),
    ]
