# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_keepers', '0010_auto_20170520_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='income',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
            preserve_default=False,
        ),
    ]
