# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_keepers', '0011_budget_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='year',
        ),
        migrations.AlterField(
            model_name='category',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_keepers.Budget'),
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
