# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_keepers', '0015_budget_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='tag',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
