# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_keepers', '0017_expense_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='note',
        ),
    ]
